//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISOFormatEntities : DbContext
    {
        public ISOFormatEntities()
            : base("name=ISOFormatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_ActualDate> tbl_ActualDate { get; set; }
        public DbSet<tbl_BuildingType> tbl_BuildingType { get; set; }
        public DbSet<tbl_ContractPDF> tbl_ContractPDF { get; set; }
        public DbSet<tbl_FormMenu> tbl_FormMenu { get; set; }
        public DbSet<tbl_LabourType> tbl_LabourType { get; set; }
        public DbSet<tbl_MasterSchedulePDF> tbl_MasterSchedulePDF { get; set; }
        public DbSet<tbl_MonthlyPlanDetail> tbl_MonthlyPlanDetail { get; set; }
        public DbSet<tbl_NameOfWork> tbl_NameOfWork { get; set; }
        public DbSet<tbl_OperationOrder> tbl_OperationOrder { get; set; }
        public DbSet<tbl_OperationOrderReg> tbl_OperationOrderReg { get; set; }
        public DbSet<tbl_OPType> tbl_OPType { get; set; }
        public DbSet<tbl_Person> tbl_Person { get; set; }
        public DbSet<tbl_PersonAndSite> tbl_PersonAndSite { get; set; }
        public DbSet<tbl_PersonType> tbl_PersonType { get; set; }
        public DbSet<tbl_PlanDate> tbl_PlanDate { get; set; }
        public DbSet<tbl_ResponsibilityType> tbl_ResponsibilityType { get; set; }
        public DbSet<tbl_Site> tbl_Site { get; set; }
        public DbSet<tbl_SOPMeetingPDF> tbl_SOPMeetingPDF { get; set; }
        public DbSet<tbl_User> tbl_User { get; set; }
        public DbSet<tbl_UserRole> tbl_UserRole { get; set; }
        public DbSet<tbl_Weather> tbl_Weather { get; set; }
        public DbSet<tbl_WeeklyPlan> tbl_WeeklyPlan { get; set; }
        public DbSet<tbl_MonthlyPlan> tbl_MonthlyPlan { get; set; }
        public DbSet<tbl_WeeklyPlanDetail> tbl_WeeklyPlanDetail { get; set; }
        public DbSet<tbl_DailyPlan> tbl_DailyPlan { get; set; }
        public DbSet<tbl_DailyPlanDetail> tbl_DailyPlanDetail { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
