//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Site
    {
        public tbl_Site()
        {
            this.tbl_ContractPDF = new HashSet<tbl_ContractPDF>();
            this.tbl_MasterSchedulePDF = new HashSet<tbl_MasterSchedulePDF>();
            this.tbl_OperationOrder = new HashSet<tbl_OperationOrder>();
            this.tbl_OperationOrderReg = new HashSet<tbl_OperationOrderReg>();
            this.tbl_PersonAndSite = new HashSet<tbl_PersonAndSite>();
            this.tbl_SOPMeetingPDF = new HashSet<tbl_SOPMeetingPDF>();
            this.tbl_WeeklyPlan = new HashSet<tbl_WeeklyPlan>();
            this.tbl_MonthlyPlan = new HashSet<tbl_MonthlyPlan>();
            this.tbl_DailyPlan = new HashSet<tbl_DailyPlan>();
        }
    
        public int SiteID { get; set; }
        public string SiteCode { get; set; }
        public string SiteName { get; set; }
        public string CustomerName { get; set; }
        public bool IsComplete { get; set; }
        public bool Active { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<tbl_ContractPDF> tbl_ContractPDF { get; set; }
        public virtual ICollection<tbl_MasterSchedulePDF> tbl_MasterSchedulePDF { get; set; }
        public virtual ICollection<tbl_OperationOrder> tbl_OperationOrder { get; set; }
        public virtual ICollection<tbl_OperationOrderReg> tbl_OperationOrderReg { get; set; }
        public virtual ICollection<tbl_PersonAndSite> tbl_PersonAndSite { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        public virtual ICollection<tbl_SOPMeetingPDF> tbl_SOPMeetingPDF { get; set; }
        public virtual ICollection<tbl_WeeklyPlan> tbl_WeeklyPlan { get; set; }
        public virtual ICollection<tbl_MonthlyPlan> tbl_MonthlyPlan { get; set; }
        public virtual ICollection<tbl_DailyPlan> tbl_DailyPlan { get; set; }
    }
}
