//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FormMenu
    {
        public int FormID { get; set; }
        public string FormDescription { get; set; }
        public string FormName { get; set; }
        public int ParentFormID { get; set; }
        public string GroupName { get; set; }
        public bool Active { get; set; }
    }
}
