//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BuildingType
    {
        public tbl_BuildingType()
        {
            this.tbl_OperationOrder = new HashSet<tbl_OperationOrder>();
            this.tbl_OperationOrderReg = new HashSet<tbl_OperationOrderReg>();
        }
    
        public int BuildingTypeID { get; set; }
        public string BuildingType { get; set; }
        public bool Active { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
        public virtual ICollection<tbl_OperationOrder> tbl_OperationOrder { get; set; }
        public virtual ICollection<tbl_OperationOrderReg> tbl_OperationOrderReg { get; set; }
    }
}
