//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MonthlyPlanDetail
    {
        public tbl_MonthlyPlanDetail()
        {
            this.tbl_ActualDate = new HashSet<tbl_ActualDate>();
            this.tbl_PlanDate = new HashSet<tbl_PlanDate>();
        }
    
        public int ID { get; set; }
        public int MOPID { get; set; }
        public int NameOfWorkID { get; set; }
        public decimal a { get; set; }
        public decimal b { get; set; }
        public Nullable<decimal> c { get; set; }
        public Nullable<decimal> d { get; set; }
        public Nullable<decimal> e { get; set; }
        public Nullable<decimal> f { get; set; }
        public Nullable<decimal> PreviousOverallWorkdone { get; set; }
        public Nullable<decimal> OverallWorkdone { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<tbl_ActualDate> tbl_ActualDate { get; set; }
        public virtual ICollection<tbl_PlanDate> tbl_PlanDate { get; set; }
        public virtual tbl_NameOfWork tbl_NameOfWork { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_MonthlyPlan tbl_MonthlyPlan { get; set; }
    }
}
