//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ResponsibilityType
    {
        public tbl_ResponsibilityType()
        {
            this.tbl_PersonAndSite = new HashSet<tbl_PersonAndSite>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<tbl_PersonAndSite> tbl_PersonAndSite { get; set; }
    }
}
