//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OPType
    {
        public tbl_OPType()
        {
            this.tbl_NameOfWork = new HashSet<tbl_NameOfWork>();
        }
    
        public int OPTypeID { get; set; }
        public string OperationPlan { get; set; }
        public bool Active { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<tbl_NameOfWork> tbl_NameOfWork { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
