//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DailyPlan
    {
        public tbl_DailyPlan()
        {
            this.tbl_DailyPlanDetail = new HashSet<tbl_DailyPlanDetail>();
        }
    
        public int DPID { get; set; }
        public int SiteID { get; set; }
        public int SubContractorID { get; set; }
        public System.DateTime Date { get; set; }
        public int WeatherID { get; set; }
        public int PreparedBy { get; set; }
        public Nullable<bool> CompletePrepare { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
        public Nullable<bool> CompleteReceive { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<bool> CompleteCheck { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual tbl_Person tbl_Person { get; set; }
        public virtual tbl_Site tbl_Site { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_User tbl_User1 { get; set; }
        public virtual tbl_User tbl_User2 { get; set; }
        public virtual tbl_User tbl_User3 { get; set; }
        public virtual tbl_User tbl_User4 { get; set; }
        public virtual tbl_Weather tbl_Weather { get; set; }
        public virtual ICollection<tbl_DailyPlanDetail> tbl_DailyPlanDetail { get; set; }
    }
}
