//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WeeklyPlanDetail
    {
        public int ID { get; set; }
        public int WOPID { get; set; }
        public int NameOfWorkID { get; set; }
        public System.DateTime PlanFromDate { get; set; }
        public System.DateTime PlanToDate { get; set; }
        public System.DateTime ActualFromDate { get; set; }
        public System.DateTime ActualToDate { get; set; }
        public string P1 { get; set; }
        public string P2 { get; set; }
        public string P3 { get; set; }
        public string P4 { get; set; }
        public string P5 { get; set; }
        public string P6 { get; set; }
        public string P7 { get; set; }
        public string A1 { get; set; }
        public string A2 { get; set; }
        public string A3 { get; set; }
        public string A4 { get; set; }
        public string A5 { get; set; }
        public string A6 { get; set; }
        public string A7 { get; set; }
        public string Remark { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual tbl_NameOfWork tbl_NameOfWork { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_WeeklyPlan tbl_WeeklyPlan { get; set; }
    }
}
