//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PlanDate
    {
        public int ID { get; set; }
        public int MPDID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tbl_MonthlyPlanDetail tbl_MonthlyPlanDetail { get; set; }
    }
}
