//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Person
    {
        public tbl_Person()
        {
            this.tbl_OperationOrder = new HashSet<tbl_OperationOrder>();
            this.tbl_OperationOrder1 = new HashSet<tbl_OperationOrder>();
            this.tbl_OperationOrder2 = new HashSet<tbl_OperationOrder>();
            this.tbl_OperationOrderReg = new HashSet<tbl_OperationOrderReg>();
            this.tbl_OperationOrderReg1 = new HashSet<tbl_OperationOrderReg>();
            this.tbl_OperationOrderReg2 = new HashSet<tbl_OperationOrderReg>();
            this.tbl_PersonAndSite = new HashSet<tbl_PersonAndSite>();
            this.tbl_User1 = new HashSet<tbl_User>();
            this.tbl_DailyPlan = new HashSet<tbl_DailyPlan>();
            this.tbl_MonthlyPlan = new HashSet<tbl_MonthlyPlan>();
            this.tbl_MonthlyPlan1 = new HashSet<tbl_MonthlyPlan>();
            this.tbl_MonthlyPlan2 = new HashSet<tbl_MonthlyPlan>();
        }
    
        public int PersonID { get; set; }
        public string PersonName { get; set; }
        public int PersonTypeID { get; set; }
        public bool Active { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<tbl_OperationOrder> tbl_OperationOrder { get; set; }
        public virtual ICollection<tbl_OperationOrder> tbl_OperationOrder1 { get; set; }
        public virtual ICollection<tbl_OperationOrder> tbl_OperationOrder2 { get; set; }
        public virtual ICollection<tbl_OperationOrderReg> tbl_OperationOrderReg { get; set; }
        public virtual ICollection<tbl_OperationOrderReg> tbl_OperationOrderReg1 { get; set; }
        public virtual ICollection<tbl_OperationOrderReg> tbl_OperationOrderReg2 { get; set; }
        public virtual tbl_PersonType tbl_PersonType { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        public virtual ICollection<tbl_PersonAndSite> tbl_PersonAndSite { get; set; }
        public virtual ICollection<tbl_User> tbl_User1 { get; set; }
        public virtual ICollection<tbl_DailyPlan> tbl_DailyPlan { get; set; }
        public virtual ICollection<tbl_MonthlyPlan> tbl_MonthlyPlan { get; set; }
        public virtual ICollection<tbl_MonthlyPlan> tbl_MonthlyPlan1 { get; set; }
        public virtual ICollection<tbl_MonthlyPlan> tbl_MonthlyPlan2 { get; set; }
    }
}
