//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PersonAndSite
    {
        public int ID { get; set; }
        public int SiteID { get; set; }
        public int PersonID { get; set; }
        public int ResponsibilityTypeID { get; set; }
        public bool Finished { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual tbl_Person tbl_Person { get; set; }
        public virtual tbl_ResponsibilityType tbl_ResponsibilityType { get; set; }
        public virtual tbl_Site tbl_Site { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
