//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Weather
    {
        public tbl_Weather()
        {
            this.tbl_DailyPlan = new HashSet<tbl_DailyPlan>();
        }
    
        public int WeatherID { get; set; }
        public string Weather { get; set; }
    
        public virtual ICollection<tbl_DailyPlan> tbl_DailyPlan { get; set; }
    }
}
